# Configuración BASE
quarkus.mongodb.database=library
mongodb.collection.books=books
mongodb.collection.users=users
mongodb.collection.orders=orders
mongodb.collection.deliverys=deliverys

# Documentación / UI
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger
quarkus.smallrye-openapi.path=/openapi

# Credenciales primer usuario
admin.email=admin@example.com
admin.password=admin

# Configuración JWT
# Issuer del token (DEBE coincidir en generación y verificación)
mp.jwt.verify.issuer=http://localhost:8080/library

# Clave pública para verificar tokens
mp.jwt.verify.publickey.location=META-INF/publicKey.pem

# Clave privada para firmar tokens
smallrye.jwt.sign.key.location=META-INF/privateKey.pem
smallrye.jwt.sign.algorithm=RS256

# Tiempo de expiración personalizado
jwt.expiration=3600

# Configuraciones adicionales importantes
quarkus.smallrye-jwt.enabled=true