# Configuración BASE

# Nombre de la base de datos
quarkus.mongodb.database=library

# Nombres de colecciones
mongodb.collection.books=books
mongodb.collection.users=users
mongodb.collection.orders=orders
mongodb.collection.deliverys=deliverys

# Documentación / UI
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger
quarkus.smallrye-openapi.path=/openapi

# Credenciales primer ususario de la aplicacion
admin.email=admin@example.com
admin.password=admin

# Configuracion de JWT

# Emisor del token JWT
smallrye.jwt.issuer=http://localhost:8080/library

# Clave pública para validar tokens entrantes (si decides proteger endpoints)
# Quarkus la usará automáticamente para verificar los tokens JWT
mp.jwt.verify.publickey.location=META-INF/publicKey.pem

# Clave privada para firmar el JWT (solo en el backend)
# El token se firma automáticamente con esta clave cuando usas Jwt.claims().sign()
smallrye.jwt.sign.key.location=META-INF/privateKey.pem

# Algoritmo usado para firmar el JWT
# RS256 es seguro y estándar (clave pública/privada)
smallrye.jwt.sign.algorithm=RS256

# Tiempo de expiración del JWT (en segundos)
# Esto no es requerido por Quarkus, pero lo usaremos en nuestro código para calcular 'exp'
jwt.expiration=3600