# Perfil PROD

# Conexión configurable via ENV, con fallback local
quarkus.mongodb.connection-string=${MONGO_CONNECTION_STRING:mongodb://localhost:27017}
quarkus.mongodb.credentials.username=${MONGO_USERNAME:}
quarkus.mongodb.credentials.password=${MONGO_PASSWORD:}
quarkus.mongodb.tls=${MONGO_TLS:true}

# Colecciones en prod
mongodb.collection.books=${MONGO_COLLECTION_BOOKS:books}
mongodb.collection.users=${MONGO_COLLECTION_USERS:users}
mongodb.collection.orders=${MONGO_COLLECTION_ORDERS:orders}
mongodb.collection.deliverys=${MONGO_COLLECTION_DELIVERYS:deliverys}

# Credenciales primer ususario de la aplicacion
admin.email=${ADMIN_EMAIL:admin@example.com}
admin.password=${ADMIN_PASSWORD:admin}

# Configuracion de JWT

# Emisor del token JWT (claim 'iss')
# Es el identificador del servicio que emite el token.
# Debe ser una URL o cadena única para producción.
# Puedes configurarlo vía variable de entorno.
mp.jwt.verify.issuer=${JWT_ISSUER:https://api.tulibreria.com}

# Ruta de la clave pública para validar tokens entrantes
# Esta ruta debe existir en el entorno de producción.
# Es seguro dejarla pública; puede ir montada desde un secret o volumen externo.
mp.jwt.verify.publickey.location=${JWT_PUBLIC_KEY_PATH:/run/secrets/publicKey.pem}

# Ruta de la clave privada para firmar el token JWT
# Esta clave NUNCA debe ir en el repositorio ni estar hardcodeada.
# Debe ser inyectada de forma segura por el entorno (Docker secret, Vault, etc.)
mp.jwt.sign.key-location=${JWT_PRIVATE_KEY_PATH:/run/secrets/privateKey.pem}

# Algoritmo de firma del JWT
# RS256 es el estándar seguro basado en clave pública/privada
mp.jwt.sign.algorithm=${JWT_SIGN_ALGORITHM:RS256}

# Tiempo de expiración del token JWT en segundos
# Esto no lo usa Quarkus directamente, pero tú sí lo usas al generarlo con Jwt.claims()
jwt.expiration=${JWT_EXPIRATION:3600}