# Perfil PROD

# Conexión configurable via ENV, con fallback local
quarkus.mongodb.connection-string=${MONGO_CONNECTION_STRING:mongodb://localhost:27017}
quarkus.mongodb.credentials.username=${MONGO_USERNAME:}
quarkus.mongodb.credentials.password=${MONGO_PASSWORD:}
quarkus.mongodb.tls=${MONGO_TLS:true}

# Colecciones en prod
mongodb.collection.books=${MONGO_COLLECTION_BOOKS:books}
mongodb.collection.users=${MONGO_COLLECTION_USERS:users}
mongodb.collection.orders=${MONGO_COLLECTION_ORDERS:orders}
mongodb.collection.deliverys=${MONGO_COLLECTION_DELIVERYS:deliverys}

# Credenciales primer ususario de la aplicacion
admin.email=${ADMIN_EMAIL:admin@example.com}
admin.password=${ADMIN_PASSWORD:admin}