#Conexion a la DB
quarkus.mongodb.connection-string=mongodb://localhost:27017
quarkus.mongodb.database=library
mongodb.collection.books=books
mongodb.collection.users=users
mongodb.collection.orders=orders
mongodb.collection.deliverys=deliverys

# Cambios de codigo reflejados automaticamente
quarkus.live-reload.password=dev

# Se habilita Swagger
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger
quarkus.smallrye-openapi.path=/openapi